---
language: python
python: "3.9"
sudo: required

services:
  - docker

install:
  - pip install -I pipenv
  - pipenv sync

jobs:
  include:
    # AMD64 - Debian Buster
    - name: "AMD64 - Debian Buster"
      os: linux
      arch: amd64
      dist: focal
      env: MOLECULE_DISTRO=debian:buster-slim
    
    # AMD64 - Debian Bullseye
    - name: "AMD64 - Debian Bullseye"
      os: linux
      arch: amd64
      dist: focal
      env: MOLECULE_DISTRO=debian:bullseye-slim
    
    # ARM64 - Debian Buster
    - name: "ARM64 - Debian Buster"
      os: linux
      arch: arm64
      dist: focal
      env: MOLECULE_DISTRO=debian:buster-slim
    
    # ARM64 - Debian Bullseye
    - name: "ARM64 - Debian Bullseye"
      os: linux
      arch: arm64
      dist: focal
      env: MOLECULE_DISTRO=debian:bullseye-slim

script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
