# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 1024
    virtualbox.cpus = 1
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "debian/jessie64"
    mysql.vm.hostname = "mysql"
    mysql.vm.network "private_network", ip:"10.0.0.2"
    mysql.vm.provision "ansible" do |ansible|
      ansible.playbook = "main.yml"
      ansible.sudo = true
      ansible.extra_vars = {
        mysql_root_password: 'vagrant',
        mysql_databases: [
          { 
            "name": 'mysql_test',
            "encoding": 'utf8'
          },
        ],
        mysql_users: [
          {
            "name": 'mysql',
            "password": 'vagrant',
            "priv": [
              'mysql_production.*:ALL',
            ]
          }
        ]
      }
    end
  end

end
