# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN mkdir -p /usr/share/man/man1

# install minimal packages for debian slim images
RUN apt-get update && \
    apt-get install -y python3 sudo bash ca-certificates iproute2 systemd systemd-sysv python3-pip && \
    apt-get clean

RUN systemctl mask getty.target 
