---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: mysql
    groups:
      - mysql_group
    image: ${MOLECULE_DISTRO:-debian:bullseye-slim}
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
scenario:
  name: mysql
verifier:
  name: ansible
